# Generated by Django 4.2.7 on 2025-11-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('output', models.TextField()),
                ('error', models.TextField(blank=True)),
                ('success', models.BooleanField(default=False)),
                ('execution_time', models.FloatField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'command_executions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServerConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=22)),
                ('connected', models.BooleanField(default=False)),
                ('last_connection', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'server_connections',
            },
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('system', 'System'), ('docker', 'Docker'), ('web', 'Web Service'), ('database', 'Database')], max_length=20)),
                ('log_content', models.TextField()),
                ('log_file_path', models.CharField(max_length=500)),
                ('lines_count', models.IntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'service_logs',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
